require('dotenv').config({ path: require('path').join(__dirname, '.env') });
const express=require('express'),path=require('path'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken');
const db=require('./db'); const {encrypt}=require('./security'); const {GOALS,SCHEMES,analyze,emi,safeSnapshot}=require('./finance'); const {answer}=require('./ai');
const app=express(),PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET;
if(!JWT_SECRET || JWT_SECRET.length < 32) throw new Error('JWT_SECRET must be set in backend/.env and be at least 32 characters long.');
app.disable('x-powered-by');app.use(express.json({limit:'1mb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Cache-Control','no-store');next();});
app.use(express.static(path.join(__dirname,'..','frontend')));
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d; const tableMap={family:'family_members',loans:'loans',insurance:'insurance',investments:'investments',goals:'goals'};
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Login required'});req.user=jwt.verify(h.slice(7),JWT_SECRET);next();}catch{return res.status(401).json({error:'Invalid or expired session'});}}
function userData(uid){const get=t=>db.prepare(`SELECT * FROM ${t} WHERE user_id=?`).all(uid);return {household:db.prepare('SELECT * FROM household WHERE user_id=?').get(uid),family_members:get('family_members'),loans:get('loans'),insurance:get('insurance'),investments:get('investments'),goals:get('goals')};}
function analysis(uid){const d=userData(uid);return analyze(d.household||{},d.family_members,d.loans,d.insurance,d.investments,d.goals);}
function err(res,e){console.error(e);res.status(400).json({error:e.message||'Invalid request'});}
app.get('/api/health',(req,res)=>res.json({ok:true,name:'The Finance Leader',version:'3.1.1'}));
app.post('/api/auth/register',async(req,res)=>{try{const b=req.body||{},email=String(b.email||'').trim().toLowerCase(),phone=String(b.phone||'').replace(/\D/g,''),aadhaar=String(b.aadhaar||'').replace(/\D/g,''),password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email))throw Error('Enter a valid email.');if(!/^\d{10}$/.test(phone))throw Error('Phone number must contain 10 digits.');if(!/^\d{12}$/.test(aadhaar))throw Error('Aadhaar number must contain 12 digits.');if(password.length<8)throw Error('Password must be at least 8 characters.');if(!b.consent)throw Error('Consent is required before storing Aadhaar data.');const hash=await bcrypt.hash(password,12);const r=db.prepare('INSERT INTO users(email,phone,aadhaar_cipher,aadhaar_last4,password_hash) VALUES(?,?,?,?,?)').run(email,phone,encrypt(aadhaar),aadhaar.slice(-4),hash);db.prepare('INSERT INTO household(user_id) VALUES(?)').run(r.lastInsertRowid);const token=jwt.sign({id:r.lastInsertRowid,email},JWT_SECRET,{expiresIn:'8h'});res.status(201).json({token,user:{email,phone,masked_aadhaar:`XXXX-XXXX-${aadhaar.slice(-4)}`}});}catch(e){err(res,e)}});
app.post('/api/auth/login',async(req,res)=>{try{const b=req.body||{},email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Invalid email or password.'});const token=jwt.sign({id:u.id,email:u.email},JWT_SECRET,{expiresIn:'8h'});res.json({token,user:{email:u.email,phone:u.phone,masked_aadhaar:`XXXX-XXXX-${u.aadhaar_last4}`}});}catch(e){err(res,e)}});
app.get('/api/me',auth,(req,res)=>{const u=db.prepare('SELECT email,phone,aadhaar_last4,created_at FROM users WHERE id=?').get(req.user.id);res.json({...u,masked_aadhaar:`XXXX-XXXX-${u.aadhaar_last4}`});});
app.get('/api/catalog',auth,(req,res)=>res.json({goals:GOALS,schemes:SCHEMES}));
app.get('/api/data',auth,(req,res)=>res.json(userData(req.user.id)));
app.put('/api/household',auth,(req,res)=>{try{const b=req.body||{};db.prepare(`UPDATE household SET monthly_income=?,monthly_other_income=?,current_savings=?,essential_expenses=?,desired_emergency_months=?,risk_profile=?,state=?,first_home_buyer=? WHERE user_id=?`).run(n(b.monthly_income),n(b.monthly_other_income),n(b.current_savings),n(b.essential_expenses),Math.max(3,Math.min(12,n(b.desired_emergency_months,6))),b.risk_profile||'moderate',String(b.state||''),b.first_home_buyer?1:0,req.user.id);res.json(db.prepare('SELECT * FROM household WHERE user_id=?').get(req.user.id));}catch(e){err(res,e)}});
const schemas={family:{cols:['name','relation','age','occupation','monthly_income','education_level','monthly_fee','annual_fee','fee_due_month','dependent'],values:b=>[b.name,b.relation,n(b.age),b.occupation||'',n(b.monthly_income),b.education_level||'',n(b.monthly_fee),n(b.annual_fee),Math.max(1,Math.min(12,n(b.fee_due_month,6))),b.dependent===false?0:1]},loans:{cols:['name','type','outstanding','annual_rate','emi','remaining_months'],values:b=>[b.name,b.type,n(b.outstanding),n(b.annual_rate),n(b.emi),Math.max(0,Math.floor(n(b.remaining_months)))]},insurance:{cols:['provider','type','premium','frequency','renewal_date','sum_assured'],values:b=>[b.provider,b.type,n(b.premium),b.frequency||'monthly',b.renewal_date||'',n(b.sum_assured)]},investments:{cols:['provider','type','current_value','monthly_contribution','annual_return_assumption','goal_id'],values:b=>[b.provider,b.type,n(b.current_value),n(b.monthly_contribution),n(b.annual_return_assumption,8),b.goal_id?Math.floor(n(b.goal_id)):null]},goals:{cols:['type','label','amount','target_year','priority','current_amount','inflation_rate'],values:b=>[b.type,GOALS[b.type].label,n(b.amount),Math.floor(n(b.target_year)),Math.max(1,Math.min(5,Math.floor(n(b.priority,3)))),n(b.current_amount),Math.max(0,Math.min(15,n(b.inflation_rate,GOALS[b.type].inflation)))]}};
for(const key of Object.keys(schemas)){app.post('/api/'+key,auth,(req,res)=>{try{const b=req.body||{};if(key==='goals'&&(!GOALS[b.type]||n(b.amount)<=0||Math.floor(n(b.target_year))<=new Date().getFullYear()))throw Error('Choose a valid future goal and positive amount.');if(!b.name&&key==='family')throw Error('Family member name is required.');if(key==='loans'&&(!b.name||n(b.emi)<0))throw Error('Loan name and valid EMI are required.');if((key==='insurance'||key==='investments')&&!b.provider)throw Error('Provider is required.');const s=schemas[key],table=tableMap[key],cols=['user_id',...s.cols],vals=[req.user.id,...s.values(b)];const r=db.prepare(`INSERT INTO ${table}(${cols.join(',')}) VALUES(${cols.map(()=>'?').join(',')})`).run(...vals);res.status(201).json(db.prepare(`SELECT * FROM ${table} WHERE id=? AND user_id=?`).get(r.lastInsertRowid,req.user.id));}catch(e){err(res,e)}});}
for(const key of Object.keys(tableMap))app.delete('/api/'+tableMap[key]+'/:id',auth,(req,res)=>{try{const r=db.prepare(`DELETE FROM ${tableMap[key]} WHERE id=? AND user_id=?`).run(n(req.params.id),req.user.id);res.status(r.changes?204:404).end();}catch(e){err(res,e)}});
app.get('/api/analysis',auth,(req,res)=>{try{const a=analysis(req.user.id);res.json({...a,health:safeSnapshot(a).health});}catch(e){err(res,e)}});
app.post('/api/loan-quote',auth,(req,res)=>{try{const p=n(req.body.principal),rate=n(req.body.annual_rate),m=Math.floor(n(req.body.months));if(p<=0||rate<0||m<=0)throw Error('Principal, rate and months must be valid.');const x=emi(p,rate,m);res.json({principal:p,annual_rate:rate,months:m,monthly_emi:x,total_repayment:x*m,total_interest:x*m-p});}catch(e){err(res,e)}});
app.get('/api/chat/history',auth,(req,res)=>res.json(db.prepare('SELECT role,content,created_at FROM chat_messages WHERE user_id=? ORDER BY id DESC LIMIT 20').all(req.user.id).reverse()));
app.post('/api/chat',auth,async(req,res)=>{try{const message=String(req.body?.message||'').trim();if(!message||message.length>800)throw Error('Enter a message up to 800 characters.');const a=analysis(req.user.id);const snap=safeSnapshot(a);const hist=db.prepare('SELECT role,content FROM chat_messages WHERE user_id=? ORDER BY id DESC LIMIT 8').all(req.user.id).reverse();db.prepare('INSERT INTO chat_messages(user_id,role,content) VALUES(?,?,?)').run(req.user.id,'user',message);const out=await answer(message,snap,hist);db.prepare('INSERT INTO chat_messages(user_id,role,content) VALUES(?,?,?)').run(req.user.id,'assistant',out.reply);res.json(out);}catch(e){err(res,e)}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'..','frontend','index.html')));
module.exports=app;
